### ISSUE TITLE
Tab close is not working in bootstrap 4

### ISSUE THREAD

**Issue by mrj2009** [nethuige/nth-tabs#10]
Tab close is not working in bootstrap 4

**Comment by mrj2009** [comment]
Uncaught TypeError: handler.tabToggleHandler is not a function
    at HTMLLIElement.<anonymous> (nth-tabs.js:331:48)
    at HTMLDivElement.dispatch (jquery-3.3.1.min.js:2:41672)
    at HTMLDivElement.v.handle (jquery-3.3.1.min.js:2:39702)
(anonymous) @ nth-tabs.js:331
dispatch @ jquery-3.3.1.min.js:2
v.handle @ jquery-3.3.1.min.js:2
